version: '2'

services:
  riri:
    container_name: "riri"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
     - ".:/var/app"
    restart: always
    ports:
      - "${WEB_PORT}:8080"
    environment:
      - "ORGANISATION_UUID=${ORGANISATION_UUID}"
      - "CAMPAIGN_UUID=${CAMPAIGN_UUID}"
    working_dir: "/var/app"
